import { Metadata } from 'next'
import { Footer } from '@/components/footer/footer'
import { Header } from '@/components/header/header'
import { Main } from '@/components/main/main'
import { ReduxProvider } from '@/store/provider'
import '@/styles/globals.scss'

export const metadata: Metadata = {
  title: 'Currencies App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='wrapper'>
          <Header/>
          <Main>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </Main>
          <Footer/>
        </div>
      </body>
    </html>
  )
}
